core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cv.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv/urls.py
from django.urls import path
from . import views

app_name = 'cv'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('create-resume/', views.resume_form, name='create-resume'),
    path('resume/<int:id>/', views.final_resume, name='final-resume'),
    path('resume/list', views.list_view, name='list'),
]

cv/models.py
from django.db import models

# Create your models here.

class Profile(models.Model):
    name = models.CharField(max_length=100)
    field = models.CharField(max_length=100, default='Job Seeker')
    nationality = models.CharField(max_length=50)
    language = models.CharField(max_length=500)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    mobile = models.CharField(max_length=100)
    summary = models.TextField()
    education = models.TextField()
    experience = models.TextField()
    skills = models.TextField()
    certificates = models.TextField()
    address_one = models.CharField(max_length=50)
    address_two = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/profile', blank=True, null=True)


    def __str__(self):
        return self.name

cv/forms.py
from django import forms
from .models import Profile

class ProfileFormItem(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

cv/views.py
from django.shortcuts import render, redirect
from .models import Profile
from .forms import ProfileFormItem
# Create your views here.

def landing(request):
    return render(request, 'landing.html')

def resume_form(request):
    form = ProfileFormItem(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('cv:landing')

    return render(request, 'add-edit-resume.html', {'form': form})


def final_resume(request, id):
    profile = Profile.objects.get(pk=id)

    context = {
        'profile': profile
    }

    return render(request, 'final-resume.html', context)

def list_view(request):
    profiles = Profile.objects.all()
    
    return render(request, 'list.html', {'profiles':profiles})



def delete_item(request, pk):
    Product.objects.get(pk=id).delete()
    return HttpResponseRedirect("/")

cv/templates/add-edit-resume.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <link href="{% static "assets/img/favicon-profile.png" %}" rel=icon>

    <!-- Title Page-->
    <title>Create Resume</title>

    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Main CSS-->
    <link href="{% static "css/main.css" %}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-02 p-t-100 p-b-50">
        <div class="wrapper wrapper--w900">
            <div class="card card-6">
                <div class="card-heading">
                    <h2 class="title">Fill Out the Form</h2>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="name">Full name</div>
                            <div class="value">
                                <input class="input--style-6" type="text" name="name">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="name">Job Field</div>
                            <div class="value">
                                <input class="input--style-6" type="text" name="field">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="name">Nationality</div>
                            <div class="value">
                                <input class="input--style-6" type="text" name="nationality">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="name">Language</div>
                            <div class="value">
                                <input class="input--style-6" type="text" name="language">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="name">Email address</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-6" type="email" name="email" placeholder="example@email.com">
                                </div>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="name">Phone number</div>
                            <div class="value">
                                <input class="input--style-6" type="text" name="phone">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Mobile number</div>
                            <div class="value">
                                <input class="input--style-6" type="text" name="mobile">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Address One</div>
                            <div class="value">
                                <input class="input--style-6" type="text" name="address_one">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Address Two</div>
                            <div class="value">
                                <input class="input--style-6" type="text" name="address_two">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Education & Degrees</div>
                            <div class="value">
                                <div class="input-group">
                                    <textarea class="textarea--style-6" name="education"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Skills & Awards</div>
                            <div class="value">
                                <div class="input-group">
                                    <textarea class="textarea--style-6" name="skills"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Work Experience</div>
                            <div class="value">
                                <div class="input-group">
                                    <textarea class="textarea--style-6" name="experience"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Certificates</div>
                            <div class="value">
                                <div class="input-group">
                                    <textarea class="textarea--style-6" name="certificates"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Summary</div>
                            <div class="value">
                                <div class="input-group">
                                    <textarea class="textarea--style-6" name="summary"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Picture</div>
                            <div class="value">
                                <div class="input-group js-input-file">
                                    <input class="input-file" type="file" name="image" id="file">
                                    <label class="label--file" for="file">Choose file</label>
                                    <span class="input-file__info">No file chosen</span>
                                </div>
                                <div class="label--desc">Upload your Picture. Max file size 2MB</div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn--radius-2 btn--blue-2" type="submit">Create Resume</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>


    <!-- Main JS-->
    <script src="{% static "js/global.js" %}"></script>

</body>
</html>
<!-- end document-->

cv/templates/final-resume.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{{ profile.name }} Profile - Final Resume</title>

    <!-- favicon -->
    <link href="{% static "assets/img/favicon-profile.png" %}" rel=icon>

    <!-- web-fonts -->
    <link href="https://fonts.googleapis.com/css?family=Hind:300,400,500,600,700" rel="stylesheet">

    <!-- font-awesome -->
    <link href="{% static "css/final_resume/font-awesome.min.css" %}" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="{% static "css/final_resume/bootstrap.min.css" %}" rel="stylesheet">

    <!-- owl carousal -->
    <link href="{% static "css/final_resume/owl.carousel.css" %}" rel="stylesheet">

    <!-- Style CSS -->
    <link href="{% static "css/final_resume/style.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div id="main-wrapper">
<!-- Page Preloader -->
<div id="preloader">
    <div id="status">
        <div class="status-mes"></div>
    </div>
</div>

<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                {% if profile.image == "" or None %}
                <div class="profile-img">
                    <img src="{% static "assets/img/img-profile.jpg" %}" class="img-responsive" alt=""/>
                </div>
                {% else %}
                <div class="profile-img">
                    <img src="{{ profile.image.url }}" class="img-responsive" alt=""/>
                </div>
                {% endif %}
                <!-- Profile Image -->
            </div>
            <div class="col-md-9">
                <div class="name-wrapper">
                    <h1 class="name">{{ profile.name }}</h1>
                    <span style="text-transform: capitalize">{{ profile.field }}</span>
                </div>
                <p>
                    {{ profile.summary }}
                </p>


                <div class="row">
                    <!-- <div class="col-md-3">
                        <div class="personal-details">
                            <strong>OCTOBER 17, 1996</strong>
                            <small>BIRTH</small>
                        </div>
                    </div> -->
                    <div class="col-md-3">
                        <div class="personal-details">
                            <strong style="text-transform: capitalize">{{ profile.nationality }}</strong>
                            <small>NATIONALITY</small>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="personal-details">
                            <strong style="text-transform: capitalize">{{ profile.language }}</strong>
                            <small>LANGUAGE</small>
                        </div>
                    </div>
                </div>

                <!-- <ul class="social-icon">
                    {% if profile.github_url %}
                    <li><a href="{{ profile.github_url }}"><i class="fa fa-github" aria-hidden="true"></i></a></li>
                    {% endif %}
                    <li><a href="{{ profile.linkedin_url }}"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                </ul> -->
            </div>
        </div>
    </div>
</header>
<!-- .header-->

<section class="section-wrapper skills-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="section-title">
                    <h2>Skills</h2>
                </div>
            </div>

            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-6">
                        <div class="progress-wrapper">

                            <div class="progress-item">
                                <h4>{{ profile.skills | linebreaks }}</h4>
                            </div>
                            <!-- .skill-progress -->

                        </div>
                        <!-- /.progress-wrapper -->
                    </div>
                </div>
                <!--.row -->
            </div>
        </div>

    </div>
    <!-- .container-fluid -->
</section>
<!-- .skills-wrapper -->

<section class="section-wrapper section-experience">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="section-title"><h2>Work Experience</h2></div>
            </div>
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-6">
                        <div class="content-item">
                            <h4>{{ profile.experience | linebreaks }}</h4>
                        </div>
                        <!-- .experience-item -->
                    </div>
            </div>
            <!--.row-->
        </div>
    </div>
    <!-- .container -->
</section>
<!-- .section-experience -->

<section class="section-education section-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="section-title"><h2>Education</h2></div>
            </div>
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <div class="content-item">
                            <h4>{{ profile.education | linebreaks }}</h4>
                        </div>
                        <!-- .experience-item -->
                    </div>
                </div>
                <!--.row-->
            </div>

        </div>
        <!--.row-->
    </div>
    <!-- .container -->
</section>
<!-- .section-education -->
<section class="section-education section-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="section-title"><h2>Certificates</h2></div>
            </div>
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <div class="content-item">
                            <h4>{{ profile.certificates | linebreaks }}</h4>
                        </div>
                        <!-- .experience-item -->
                    </div>
                </div>
                <!--.row-->
            </div>

        </div>
        <!--.row-->
    </div>
    <!-- .container -->
</section>

<section class="section-contact section-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="section-title">
                    <h2>Contact</h2>
                </div>
            </div>

            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-3">
                        <address>
                            <strong>Address</strong><br>
                            {{ profile.address_one }}<br>
                            {{ profile.address_two }}

                        </address>
                    </div>
                    <div class="col-md-3">
                        <address>
                            <strong>Phone Number</strong><br>
                            {{ profile.phone }}
                        </address>
                    </div>
                    <div class="col-md-3">
                        <address>
                            <strong>Mobile Number</strong><br>
                            {{ profile.mobile }}
                        </address>
                    </div>
                    <div class="col-md-3">
                        <address>
                            <strong>Email</strong><br>
                            <a href="mailto:{{ profile.email }}">{{ profile.email }}</a>
                        </address>
                    </div>

                </div>
                <!--.row-->

                
            </div>
        </div>
        <!--.row-->

    </div>
    <!--.container-fluid-->
</section>
<!--.section-contact-->

<footer class="footer">
    <div class="copyright-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="copytext">&copy;2021 CV Generator, All rights reserved | Design By: <a
                            href="mailto:imanashoorii.77@gmail.com">Iman Ashoori</a></div>
                </div>
            </div>
            <!--.row-->
        </div>
        <!-- .container-fluid -->
    </div>
    <!-- .copyright-section -->
</footer>
<!-- .footer -->

</div>
<!-- #main-wrapper -->

<!-- jquery -->
<script src="{% static "js/final_resume/jquery-2.1.4.min.js" %}"></script>
<!-- Bootstrap -->
<script src="{% static "js/final_resume/bootstrap.min.js" %}"></script>
<!--owl carousal-->
<script src="{% static "js/final_resume/owl.carousel.min.js" %}"></script>
<!--theme script-->
<script src="{% static "js/final_resume/scripts_profile.js" %}"></script>
</body>
</html>

cv/templates/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>CV Generator - Easy Resume Builder</title>
        <!-- Favicon-->
        <link href="{% static "assets/img/favicon-profile.png" %}" rel=icon>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "css/styles.css" %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">CV Generator</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url "cv:list" %}">List</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">Your Favorite Source To Make Your CV </h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 font-weight-light mb-5">Start creating your CV can help you find better job opportunities using this simple app! Just click on the link below and start creating, no strings attached!</p>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url "cv:create-resume" %}">Let`s Start !</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- Contact-->
        <section class="page-section" id="contact">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="mt-0">Let's Get In Touch!</h2>
                        <hr class="divider my-4" />
                        <p class="text-muted mb-5">Ready to start your next project with me? Give me a call or send me an email and I will get back to you as soon as possible!</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                        <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                        <div>+98 921 237 6674</div>
                    </div>
                    <div class="col-lg-4 mr-auto text-center">
                        <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                        <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
                        <a class="d-block" href="mailto:imanashoorii.77@gmail.com">imanashoorii.77@gmail.com</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted">Copyright © 2021 - Iman Ashoori</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static "js/scripts.js" %}"></script>
    </body>
</html>

cv/templates/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resume List</title>
    <link href="{% static "assets/img/favicon-profile.png" %}" rel=icon>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            {% for profile in profiles %}
            <div class="col s12 m4 mt-5">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{ profile.image.url }}" alt="Card image cap">
                    <div class="card-body">
                    <h5 class="card-title">{{ profile.name }}</h5>
                    <a href="{% url "cv:final-resume" profile.id %}" class="btn btn-warning mt-2">Resume</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    














    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
</body>
</html>